### ISSUE TITLE
after recent commit in mongodb module, the loopback-component-storage-mongo does not work anymore

### ISSUE THREAD

**Issue by raghav135** [jdrouet/loopback-component-storage-mongo#10]
After this commit:
https://github.com/mongodb/node-mongodb-native/commit/39102e11d6c905986b0971a49ace2afb770d87b2

We are getting below issue:

$ node .
Connection fails:  { MongoError: option host is not supported
    at validOptions (/home/rsr/work/ev-foundation/node_modules/mongodb/lib/mongo_client.js:50:14)
    at Function.MongoClient.connect (/home/rsr/work/ev-foundation/node_modules/mongodb/lib/mongo_client.js:194:13)
    at MongoStorage.connect (/home/rsr/work/ev-foundation/node_modules/loopback-component-storage-mongo/lib/index.js:53:34)
    at Object.exports.initialize (/home/rsr/work/ev-foundation/node_modules/loopback-component-storage-mongo/lib/index.js:559:26)

I feel the best fix can be to change the package.json dependency of mongodb to 2.2.22 , request your help for quick fix : )

**Comment by pkgulati** [comment]
For same issue in loopback-connector-mongodb,https://github.com/strongloop/loopback-connector-mongodb/issues/344, mongodb has been locked to 2.2.22.
