### ISSUE TITLE
Content-Disposition filename issue.

### ISSUE THREAD

**Issue by xieyang784** [jdrouet/loopback-component-storage-mongo#14]
In lib/index.js round 232 lines:
```
MongoStorage.prototype.__download = function(file, res, callback) {
    var gfs, read;
    if (callback == null) {
      callback = (function() {});
    }
    gfs = Grid(this.db, mongodb);
    read = gfs.createReadStream({
      _id: file._id
    });
    res.set('Content-Disposition', "attachment; filename=\"" + file.filename + "\"");
    res.set('Content-Type', file.metadata.mimetype);
    res.set('Content-Length', file.length);
    return read.pipe(res);
  };
```

If **file.filename** contains Chinese code or other un-standard code express will throw error:
```
TypeError: The header content contains invalid characters
    at validateHeader (_http_outgoing.js:492:11)
    at ServerResponse.setHeader (_http_outgoing.js:496:3)  
```

So change:
`res.set('Content-Disposition', "attachment; filename=\"" + file.filename + "\"");`
to:
`res.attachment(file.filename);`
will correct this issue.

**Comment by xieyang784** [comment]
@jdrouet please help review it, thanks.
